Hello this is a markdown cell, be carefull
# This is a heading

--------------------------------------------------------------

## From here we will begin python fundamentals

In [3]:
a = 10 
print(a)

10


In [ ]:
print (type(a))

<class 'int'>


In [ ]:
String = Python 
print(String)

NameError: name 'Python' is not defined

In [4]:
String = "Abdul"
print(String)
print(type(String))

Abdul
<class 'str'>


For String data type we have to put them in double quotes, and that is the reason it is giving error when we assign it first time

In [5]:

new_dt = None
print (new_dt)
print (type(new_dt))

None
<class 'NoneType'>


There is None data type which is a python specific data type

### Multiple Assignments

In [6]:
a , b = 10, 20

print ("The value of a is :", a)
print ("The value of b is :", b)

The value of a is : 10
The value of b is : 20


In [7]:
a = 35
b = 78

print(a)
print(b)

35
78


In [8]:
a = 56
b = 89

a, b = b,a

print("The value of a is :", a)
print("The value of b is :", b)

The value of a is : 89
The value of b is : 56


### Type casting - converting one type of data into another

In [9]:
marks = 71.80
print(marks)
print(type(marks))

71.8
<class 'float'>


In [10]:
int_marks = int(marks)
print(int_marks)
print(type(int_marks))

71
<class 'int'>


In [11]:
intg = 78
print(intg)
print(type(intg))

str_cnv = float(intg)
print(str_cnv)
print(type(str_cnv))

78
<class 'int'>
78.0
<class 'float'>


### Data structures in Python
There are 4 types of Data Structures in Python
1) Tuple
2) List
3) Dictionary
4) Set

### 1. Tuple

In [12]:
first_tuple = (10, 'Messi', 7, 'Ronaldo') # Use round brackets () to create a tuple
print(first_tuple)

(10, 'Messi', 7, 'Ronaldo')


In the above example, \
The 1st value has an index 0 \
2nd value has index 1 \
3rd value has index 2 \
and the 4th value has index 3. This is called indexing (Left to Right indexing)

first_tuple = (10, 'Messi', 7, 'Ronaldo') \
The variable name 'first_tuple' is holding a group of values in a tuple data structure format.

----------------------------------------------------------------------------------
first_tuple[0] - Whenever you use an index to access a value or a group of values, you should use the variable name along with the square bracket.

In [13]:
print(first_tuple[0])

10


In [14]:
first_tuple[0] = 10

TypeError: 'tuple' object does not support item assignment

- We are getting an error above because tuple is an immutable datastructure, which means values once stored in tuple cannot be changed.

-----------------------------------------------------------------------------------------------------------------------
Suppose we want to access the index 0 and index 1, so here we take help of a concept called Slicing.

In [15]:
first_tuple[0:2]

(10, 'Messi')

Here the start index is inclusive which means if we want the element 0, it access the element 0 and then retrive it. But on the other hand the end index is always inclusive only until n-1

In [16]:
# How to access the 1st, 2nd and the 3rd index
first_tuple[1:4]

('Messi', 7, 'Ronaldo')

In [17]:
# Or we can do it like this
first_tuple[1:]

('Messi', 7, 'Ronaldo')

### 2. List

In [18]:
first_list = ["Mark", 102, 23.6, True] # Use only square brackets [] to create list

In [19]:
# Access the first index
first_list[0]

'Mark'

In [20]:
# Access the first 3 index
first_list[0:3]

['Mark', 102, 23.6]

In built method of list

In [21]:
# Adding value at the end of the list
first_list.append("Dawg")

In [22]:
first_list

['Mark', 102, 23.6, True, 'Dawg']

To add the value at a particular index position we will use insert method. Here the first value specifies the index position and the second value specifies the value to be inserted.

In [23]:
first_list.insert(1, "Mouse")

In [24]:
first_list

['Mark', 'Mouse', 102, 23.6, True, 'Dawg']

pop method deletes the value present at the specified index position and also returns the value that has been deleted.

In [25]:
first_list.pop(3)

23.6

In [26]:
first_list

['Mark', 'Mouse', 102, True, 'Dawg']

To replace or update a value.

In [27]:
first_list[1] = 33

In [28]:
first_list

['Mark', 33, 102, True, 'Dawg']

Remove. This method always accepts the value to be removed, and it deletes only the first instances of the specified value from the list.

In [29]:
first_list.append("Mouse")

In [30]:
first_list

['Mark', 33, 102, True, 'Dawg', 'Mouse']

In [31]:
first_list.remove("Mouse")

In [32]:
first_list

['Mark', 33, 102, True, 'Dawg']

In [33]:
first_list[-1]

'Dawg'

In [34]:
first_list[-2:]

[True, 'Dawg']

### 3. Dictionary
Dictionary is a Mutable type of Data Structure. The values are stored along with keys i.e as a key-value pair.
Use curly brackets {} to create dictionary.\
Good practice is to have unique key-values.

In [35]:
age_dict = {'John':20, 'Johnny':22, 'Jack':24, 'Sam':30}

In [36]:
# To access only the keys
age_dict.keys()

dict_keys(['John', 'Johnny', 'Jack', 'Sam'])

In [37]:
# To access only the values
age_dict.values()

dict_values([20, 22, 24, 30])

In [38]:
# To access a particular value, only use it's key
age_dict['Jack']

24

In [39]:
# To update the a particular value, we have to provide both key and the value.
age_dict.update({'Jack':26})

In [40]:
age_dict

{'John': 20, 'Johnny': 22, 'Jack': 26, 'Sam': 30}

In [41]:
# We can also store multiple values for keys
age_dict = {'John': ["john@sl.com", 1000, 20], 'Johny': ["john@sl.com", 1001, 22], 'Sam': ["sam@sl.com", 1002, 24], 'Jack': ["jack@sl.com", 1003, 28]}

In [42]:
age_dict

{'John': ['john@sl.com', 1000, 20],
 'Johny': ['john@sl.com', 1001, 22],
 'Sam': ['sam@sl.com', 1002, 24],
 'Jack': ['jack@sl.com', 1003, 28]}

In [43]:
# To delete a particular value or record
del age_dict["Jack"]

In [44]:
age_dict

{'John': ['john@sl.com', 1000, 20],
 'Johny': ['john@sl.com', 1001, 22],
 'Sam': ['sam@sl.com', 1002, 24]}

In [45]:
# To access multiple values in a dictionary data structure use the 'key' and the 'index'
age_dict['Johny'][0:2]

['john@sl.com', 1001]

### 4. Set - Unordered collection of unique elements

In [46]:
car_brand_sur = ["Audi", "BMW", "Ferrari", "BMW", "Lamborghini", "Benz", "Audi"]
print(car_brand_sur)

['Audi', 'BMW', 'Ferrari', 'BMW', 'Lamborghini', 'Benz', 'Audi']


In [47]:
car_brand_sur_set = set(car_brand_sur)

In [48]:
print(car_brand_sur_set)

{'BMW', 'Lamborghini', 'Benz', 'Audi', 'Ferrari'}


We can absorve from the above that, list supports duplicate values while a set dosen't.

In [49]:
fruit_name_1 = {'Apples', 'Oranges', 'Mangoes', 'Apple', 'Banana'}
print(fruit_name_1)

{'Oranges', 'Banana', 'Apples', 'Apple', 'Mangoes'}


In [50]:
fruit_name_2 = {'Grapes', 'Oranges', 'Peaches', 'Berries', 'Apples'}
print(fruit_name_2)

{'Grapes', 'Oranges', 'Peaches', 'Berries', 'Apples'}


AND operator in SET is equivalent to finding out the intersection of sets.

In [51]:
fruit_name_1 & fruit_name_2

{'Apples', 'Oranges'}

In [52]:
emp_dict = {'Jenny': [1001, 'jenny@sl.com'], 'Peter': [1002, 'peter@sl.com']}

In [53]:
emp_dict['Peter'][1]

'peter@sl.com'

In [54]:
emp_dict.update({'Jenny':[1001, 'jenny@sl.com', 35]})

In [55]:
emp_dict

{'Jenny': [1001, 'jenny@sl.com', 35], 'Peter': [1002, 'peter@sl.com']}

## Loops

In [56]:
num_list = [1,2,3,4]

res_list = []

for i in num_list:
    res_list.append(i*i) # Tab spaces are called indendation in python

print(res_list)

[1, 4, 9, 16]


## Functions
Functions are used to modularise the code and to also reuse the code wherever necessary.

In [57]:
def add(a,b):
    c = a + b
    return c


In [58]:
x = 10
y = 20

output = add(x,y)
print("The sum of x & y is", output)

The sum of x & y is 30


# Numpy
Creating Numpy array or ndarrays

In [59]:
import numpy as np

In [60]:
my_list = [100, 101, 102, 103, 104]

my_ndarray = np.array(my_list)

print(type(my_ndarray))

<class 'numpy.ndarray'>


### Attribute of ndarray - ndim, shape, size, dtype

### ndim

In [61]:
np_city = np.array(["Delhi", "Mumbai", "Kolkata", "Bangalore"])

np_city.ndim

1

In [62]:
np_city_and_states = np.array([["Delhi", "Mumbai", "Kolkata", "Bangalore"], ["Delhi", "Maharashtra", "West Bengal", "Karnataka"]])

np_city_and_states.ndim

2

### Shape

In [63]:
np_city_and_states = np.array([["Delhi", "Mumbai", "Kolkata", "Bangalore"], ["Delhi", "Maharashtra", "West Bengal", "Karnataka"]])

np_city_and_states.shape

(2, 4)

### Size

In [64]:
np_city_and_states.size

8

### Dtype

In [65]:
np_city_and_states.dtype

dtype('<U11')

### Basic Operation on NumPy 

1. Mathematical Operation – Addition, Subtraction, Multiplication, Division and Exponentiation
2. Logical Operation – And, Or Not
3. Comparison Operation – Greater, Greater or equal, Less, Less or equal, Equal, Not equal.


In [66]:
distance = np.array([10, 20, 30, 40, 50])
time = np.array([0.3, 0.5, 0.7, 0.9, 0.8])

speed = distance / time


In [67]:
print(speed)

[33.33333333 40.         42.85714286 44.44444444 62.5       ]


In [68]:
distance = distance * 2
print(distance)

[ 20  40  60  80 100]


In [69]:
distance_2 = np.array([11, 12, 22, 33, 45, 67])

distance - distance_2

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

From the above we could infer that while trying to perform mathematical operations, the ndarrays should be of equal shape

In [70]:
distance_3 = np.array([11, 12, 22, 33, 45])

distance - distance_3

array([ 9, 28, 38, 47, 55])

### How to access array elements using indexing

In [71]:
dist_covered = np.array([[2,4,6,8],[3,6,9,12]])
print("The distance covered by the 2 cars in 4 different rides are: ")
print("-------------------------------------------------------------")
print(dist_covered)



The distance covered by the 2 cars in 4 different rides are: 
-------------------------------------------------------------
[[ 2  4  6  8]
 [ 3  6  9 12]]


In [72]:
dist_covered.ndim

2

    0 1 2 3
0 [[2  4  6  8] \
1  [3  6  9  12]]

Here in this matrix we have row index and column index.

In [73]:
# Here 0 represents first row
dist_covered[0]

array([2, 4, 6, 8])

In [74]:
# Here 1 reperesents 2nd row
dist_covered[1]

array([ 3,  6,  9, 12])

The value in the 1st position indicates the index value of the rows, and the value in the 2nd position indicates the value of the columns. '#' means to select everything.


In [75]:
dist_covered[0,:]

array([2, 4, 6, 8])

In [76]:
dist_covered[1,:]

array([ 3,  6,  9, 12])

In [77]:
# How to retrieve a particular value. Lets say 2
dist_covered[0,0]

2

In [78]:
# To access 3rd column
dist_covered[:,2]

array([6, 9])

In [79]:
# To access the values [2  4] \
#                      [3  6] 
dist_covered[:,:2]

array([[2, 4],
       [3, 6]])

In [80]:
# To access the values [4  6] \
#                      [6  9] 
dist_covered[:,1:3]

array([[4, 6],
       [6, 9]])

### Conditional Selection

In [81]:
dist_covered

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [82]:
dist_covered > 4

array([[False, False,  True,  True],
       [False,  True,  True,  True]])

In [83]:
bool_array = dist_covered > 4

In [84]:
dist_covered[bool_array]

array([ 6,  8,  6,  9, 12])

In [85]:
# Greater than condition
dist_covered[dist_covered > 4]

array([ 6,  8,  6,  9, 12])

In [86]:
# Equal to condition
dist_covered[dist_covered == 6]

array([6, 6])

In [87]:
# Not equal to condition
dist_covered[dist_covered != 4]

array([ 2,  6,  8,  3,  6,  9, 12])

### Universal Function or Ufunc 
These are in-built mathematical functions available in numpy

In [88]:
# Calculating the number of Square root of these number
num_array = np.array([4, 16, 25, 36, 49])

print("Square of these numbers are:")
print(np.sqrt(num_array))

Square of these numbers are:
[2. 4. 5. 6. 7.]


In [89]:
# Calculating the average of the above number

print("The average of these number is")
print(np.mean(num_array))

The average of these number is
26.0


In [90]:
print("Standard Deviation of the above number is:")
print(np.std(num_array))

Standard Deviation of the above number is:
15.582040944625964


In [91]:
print("Variance of the above number is:")
print(np.var(num_array))

print("Median of the above number is:")
print(np.median(num_array))

Variance of the above number is:
242.8
Median of the above number is:
25.0


In [92]:
# To round off the values, we can do that using the round and the ceil function

num_array_2 = np.array([71.6, 56.4, 89.9, 67.4])

In [93]:
np.round([num_array_2])

array([[72., 56., 90., 67.]])

In [94]:
np.ceil([num_array_2])

array([[72., 57., 90., 68.]])

### Shape Manipulation
Here we will be learn to 
- Flatten the array
- Resize the array
- Split the array 
- Stack the array
- Reshape the array.   

In [95]:
dist_covered

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [96]:
# Ravel function will flatten the array into 1 dimentional array
dist_covered.ravel()

array([ 2,  4,  6,  8,  3,  6,  9, 12])

In [97]:
dist_covered.reshape(4,2)

array([[ 2,  4],
       [ 6,  8],
       [ 3,  6],
       [ 9, 12]])

In [98]:
dist_covered.reshape(8,1)

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [ 3],
       [ 6],
       [ 9],
       [12]])

### Splitting the numpy array
Both hsplit and vsplit will result in sub-arrays of equal size

In [99]:
# H-Split

np.hsplit(dist_covered,2)

[array([[2, 4],
        [3, 6]]),
 array([[ 6,  8],
        [ 9, 12]])]

In [100]:
dist_covered_2 = np.array([[2,4,6,8],[3,6,9,12],[1,2,3,4],[9,10,11,12]])
dist_covered_2

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [101]:
# V-split splits the array row wise
np.vsplit(dist_covered_2,2)

[array([[ 2,  4,  6,  8],
        [ 3,  6,  9, 12]]),
 array([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]])]

In [102]:
dist_covered_3 = np.array([[2,6,9,10],[4,7,12,45]])

In [103]:
print(dist_covered)

[[ 2  4  6  8]
 [ 3  6  9 12]]


In [104]:
print(dist_covered_3)

[[ 2  6  9 10]
 [ 4  7 12 45]]


In [105]:
# Stacking the values
# H-Stack

np.hstack((dist_covered, dist_covered_3))

array([[ 2,  4,  6,  8,  2,  6,  9, 10],
       [ 3,  6,  9, 12,  4,  7, 12, 45]])

In [106]:
# V-Stack

print(np.vstack((dist_covered,dist_covered_3)))

[[ 2  4  6  8]
 [ 3  6  9 12]
 [ 2  6  9 10]
 [ 4  7 12 45]]


In [107]:
print(dist_covered)
print("--------------")

print(dist_covered_2)

[[ 2  4  6  8]
 [ 3  6  9 12]]
--------------
[[ 2  4  6  8]
 [ 3  6  9 12]
 [ 1  2  3  4]
 [ 9 10 11 12]]


When we are stacking arrays, make sure both the arrays are of same size. Below it is shown that if we do not follow this rule it will result in an error

In [108]:
np.hstack((dist_covered, dist_covered_2))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 4

In [109]:
num_array_3 = [[3, 10, 15, 20, 25, 30], [1, 2, 3, 4, 5, 6]]
num_array_3 = np.array(num_array_3)
print(num_array_3[0:2, 1:3])

[[10 15]
 [ 2  3]]


In [110]:
num_array_4 = [3, 10, 15, 20, 25, 30]
num_array_4 = np.array(num_array_4)
print(num_array_4 * 2)

[ 6 20 30 40 50 60]


Built-in methods to generate Arrays

1. Arange - Arange is a function that is used to create a sequence of numbers with a specified start, end, and step size.

In [111]:
np.arange(0, 20) # Here the first value is inclusive and the last value is not.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [112]:
# Specify start, stop and step value as input
np.arange(0,21,5)

array([ 0,  5, 10, 15, 20])

2. Zeroes - Generate arrays of 0s

In [113]:
# Specify the count of 0s required in an array
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [114]:
# Specify the number of rows and column
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [115]:
np.arange(0,20)[0::5]

array([ 0,  5, 10, 15])

3. Ones - Generate arrays of 1s

In [116]:
np.ones(11, dtype='int')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [117]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

4. Linspace - Linspace is a function used to create a sequence of evenly spaced values over a specified range. Specifies Start, Stop and number of values between them. Values generated in linspace are of float type.

In [118]:
np.linspace(0,20,5, dtype='int')

array([ 0,  5, 10, 15, 20])

In [119]:
np.linspace(0,20,50, dtype='float')

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

5. Eye - Eye is a function that is used to create a 2-dimensional square identity matrix or an identity matrix with a specified number of rows and columns. An identity matrix is a special type of square matrix where all the diagonal elements are equal to 1, and all other elements are equal to 0.

6. Random - Random module provides a wide range of functions for generating random numbers, random arrays, and performing various random sampling and probability distribution operations. Below are the options to create random numbered array.
- rand(): Generate random numbers from a uniform distribution over the interval [0, 1).

In [120]:
np.random.rand(5)

array([0.48054317, 0.02570104, 0.98881285, 0.85261041, 0.3256079 ])

In [121]:
np.random.rand(3,3)

array([[0.99971807, 0.36877882, 0.64002905],
       [0.40104785, 0.8411409 , 0.24042425],
       [0.56528056, 0.07193386, 0.19413367]])

- randn(): Generate random numbers from a standard normal (Gaussian) distribution.

In [122]:
np.random.randn(5)

array([ 0.44231204,  1.09858055,  1.16767654, -0.79497748, -0.66241685])

- randint(): Generate random integers within a specified range.

In [123]:
np.random.randint(1, 11) # This will return random interger between the values of 1 and 11 where 11 will be excluded.

2

In [124]:
np.random.randint(5, 30, 10) # This will return 10 random interger between 5 and 30.

array([27, 15,  7, 19, 16, 23, 18, 11, 20, 13])

## Pandas

### 1. Series 

How to create series object from list

In [125]:
import pandas as pd

In [126]:
my_list = ['a', 'b', 'c', 'd', 'e']

first_series = pd.Series(my_list)
first_series

0    a
1    b
2    c
3    d
4    e
dtype: object

How to create a series object from a numpy array

In [127]:
import numpy as np
num_array = [1,2,3,4,5]

num_series = pd.Series(num_array)
num_series

0    1
1    2
2    3
3    4
4    5
dtype: int64

Creating a series from dictionary

In [128]:
fruit_dict = {'Apple':50, 'Mango':100, 'Banana':500, 'Peach':150, 'Pineapple':60}

fruit_series = pd.Series(fruit_dict)
fruit_series

Apple         50
Mango        100
Banana       500
Peach        150
Pineapple     60
dtype: int64

In [129]:
num_arr = [2,4,7,89]

num_series_1 = pd.Series(num_arr)
num_series_1

0     2
1     4
2     7
3    89
dtype: int64

In [130]:
num_series_2 = pd.Series([101, 102, 103, 104, 105], index = ['Ajax', 'Bahubali', 'Sam', 'Jam', 'Diesel'])
num_series_2

Ajax        101
Bahubali    102
Sam         103
Jam         104
Diesel      105
dtype: int64

In [131]:
num_series_2[2]

C:\Users\Admin\AppData\Local\Temp\ipykernel_9348\3348623304.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  num_series_2[2]


103

In [132]:
num_series_2.loc[['Ajax', 'Sam', 'Diesel']]

Ajax      101
Sam       103
Diesel    105
dtype: int64

Vectorizing Operations in Series

In [133]:
first_vector_series = pd.Series([1,2,3,4,5], index=['a', 'b', 'c', 'd', 'e'])
second_vector_series = pd.Series([23, 45, 12, 67, 56], index=['a', 'b', 'c', 'd', 'e'])

first_vector_series + second_vector_series

a    24
b    47
c    15
d    71
e    61
dtype: int64

In [134]:
third_vector_series = pd.Series([6, 7, 8, 9, 10], index=['b', 'c', 'a', 'e', 'd'])

first_vector_series + third_vector_series

a     9
b     8
c    10
d    14
e    14
dtype: int64

Problems when the labels of Series are MISMATCHED or UNEQUAL

In [135]:
fourth_vector_series = pd.Series([11, 23, 35, 47, 79], index=['a', 'b', 'c', 'f', 'g'])

first_vector_series + fourth_vector_series

a    12.0
b    25.0
c    38.0
d     NaN
e     NaN
f     NaN
g     NaN
dtype: float64

### 2. Data Frames

In [136]:
olympic_list = {"Host City": ['Tokyo', 'London', 'Beijing', 'Athens', 'Sydney', 'Greece', 'France'], 
                "Year": [2021, 2012, 2008, 2004, 2000, 1996, 1992],
                 "No. of countries": [202, 205, 204, 201, 200, 195, 190]}

print(olympic_list)

{'Host City': ['Tokyo', 'London', 'Beijing', 'Athens', 'Sydney', 'Greece', 'France'], 'Year': [2021, 2012, 2008, 2004, 2000, 1996, 1992], 'No. of countries': [202, 205, 204, 201, 200, 195, 190]}


In [137]:
olympic_df = pd.DataFrame(olympic_list)
olympic_df # View of the data frame

Host City  Year  No. of countries
0     Tokyo  2021               202
1    London  2012               205
2   Beijing  2008               204
3    Athens  2004               201
4    Sydney  2000               200
5    Greece  1996               195
6    France  1992               190

In [138]:
print(olympic_df) # print of the data frame

  Host City  Year  No. of countries
0     Tokyo  2021               202
1    London  2012               205
2   Beijing  2008               204
3    Athens  2004               201
4    Sydney  2000               200
5    Greece  1996               195
6    France  1992               190


- The numbers that we are able to see here (to the left of the 'Host City') column are 'Labels' indices are always hidden.
- Column names like 'Host City', 'Year', 'No. of countries' are column labels

In [139]:
# To extract a single column
olympic_df["Host City"]

0      Tokyo
1     London
2    Beijing
3     Athens
4     Sydney
5     Greece
6     France
Name: Host City, dtype: object

In [140]:
# To extract multiple column
olympic_df[["Host City", "No. of countries"]]

Host City  No. of countries
0     Tokyo               202
1    London               205
2   Beijing               204
3    Athens               201
4    Sydney               200
5    Greece               195
6    France               190

In [141]:
olympic_df.iloc[0:2,0:2] # the first value represents the row indices & the second value represents the column indices

Host City  Year
0     Tokyo  2021
1    London  2012

In [142]:
# Remember that in loc 0,1,2 are labels so, the concept of inclusiveness and exclusiveness doesn't exist.

olympic_df.loc[0:2, ['Host City', 'Year', 'No. of countries']] 

Host City  Year  No. of countries
0     Tokyo  2021               202
1    London  2012               205
2   Beijing  2008               204

Attributes of Data Frame
- dtype
- column
- axes
- shape
- size
- ndim
- Transpose


In [143]:
# To list all the column in a Data Frame
olympic_df.columns

Index(['Host City', 'Year', 'No. of countries'], dtype='object')

In [144]:
# To present the datatypes of the values in all column
olympic_df.dtypes

Host City           object
Year                 int64
No. of countries     int64
dtype: object

In [145]:
# To present the indices of rows and columns
olympic_df.axes

[RangeIndex(start=0, stop=7, step=1),
 Index(['Host City', 'Year', 'No. of countries'], dtype='object')]

In [146]:
# To know the number of rows and column as a tuple
olympic_df.shape

(7, 3)

In [147]:
# To know the total number of element present in a Data Frame
olympic_df.size

21

In [148]:
# To know the number of dimensions of the Data Frame
olympic_df.ndim

2

In [149]:
# To transpose the data
olympic_df.T

0       1        2       3       4       5       6
Host City         Tokyo  London  Beijing  Athens  Sydney  Greece  France
Year               2021    2012     2008    2004    2000    1996    1992
No. of countries    202     205      204     201     200     195     190

In [150]:
# To see the top 5 records
olympic_df.head()

Host City  Year  No. of countries
0     Tokyo  2021               202
1    London  2012               205
2   Beijing  2008               204
3    Athens  2004               201
4    Sydney  2000               200

In [151]:
# To see the last 5 records
olympic_df.tail()

Host City  Year  No. of countries
2   Beijing  2008               204
3    Athens  2004               201
4    Sydney  2000               200
5    Greece  1996               195
6    France  1992               190

To see the statistical summary of Data Frame. These statistics include count, mean, standard deviation, minimum, 25th percentile, median (50th percentile), 75th percentile, and maximum values. But describe method will only show numerical column by default.

In [152]:
olympic_df.describe()

Year  No. of countries
count     7.000000          7.000000
mean   2004.714286        199.571429
std       9.911513          5.318432
min    1992.000000        190.000000
25%    1998.000000        197.500000
50%    2004.000000        201.000000
75%    2010.000000        203.000000
max    2021.000000        205.000000

To see the statistical summary of non numerical column. We can use describe method for non numerical column but it will not return the same statistics as it does for numerical columns. Instead, it will return non-numerical data, such as:

- Count: The number of non-empty values in the column.
- Unique: The number of unique values in the column.
- Top: The most frequent value in the column. 
- Freq: The frequency of the most frequent value in the column. 


In [153]:
olympic_df.describe(include='all')

Host City         Year  No. of countries
count          7     7.000000          7.000000
unique         7          NaN               NaN
top        Tokyo          NaN               NaN
freq           1          NaN               NaN
mean         NaN  2004.714286        199.571429
std          NaN     9.911513          5.318432
min          NaN  1992.000000        190.000000
25%          NaN  1998.000000        197.500000
50%          NaN  2004.000000        201.000000
75%          NaN  2010.000000        203.000000
max          NaN  2021.000000        205.000000

Info method. 

The method will provide information such as:

- The number of rows (entries).
- The number of columns (variables).
- The names of columns (for DataFrames).
- The data type of each column.
- The number of non-null values in each column.
- The memory usage of the DataFrame or Series.

In [154]:
olympic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Host City         7 non-null      object
 1   Year              7 non-null      int64 
 2   No. of countries  7 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes


------------------------------------------------------------------------------------------------------------------
Methods to apply a function on a Data Frame
- applymap (Now 'map')
- apply

Applying function on the Data Frame

To apply a function to a Data Frame we will use 'applymap' method. Here we have to use applymap method on the Data Frame variable, and within this function we have to pass the function alone without any parameters. And this function will be called with every value of the Data Frame.

In [155]:
df_movie = pd.DataFrame({"movie_1":[5,4,3,5,1],"movie_2":[2,3,4,5,1]},index=["Tom","Jeff","Peter","Ram","Paul"])
df_movie

movie_1  movie_2
Tom          5        2
Jeff         4        3
Peter        3        4
Ram          5        5
Paul         1        1

In [156]:
# We are defining a function to assign corresponding grades for the ratings
def movie_grade (rating):
    if rating == 5:
        return "A"
    if rating == 4:
        return "B"
    if rating == 3:
        return "C"
    else:
        return "D"


In [157]:
# Testing the function for its functionality
movie_grade(5)

'A'

In [158]:
# applymap is the method that should be used to apply functions on a dataframe

df_movie.applymap(movie_grade)

C:\Users\Admin\AppData\Local\Temp\ipykernel_9348\4001032186.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_movie.applymap(movie_grade)


movie_1 movie_2
Tom         A       D
Jeff        B       C
Peter       C       B
Ram         A       A
Paul        D       D

In [159]:
df_movie.map(movie_grade)

movie_1 movie_2
Tom         A       D
Jeff        B       C
Peter       C       B
Ram         A       A
Paul        D       D

In [160]:
# We can use the 'apply' method to apply the function only on specific column
df_movie["movie_1"].apply(movie_grade)

Tom      A
Jeff     B
Peter    C
Ram      A
Paul     D
Name: movie_1, dtype: object