Hello this is a markdown cell, be carefull
# This is a heading

--------------------------------------------------------------

## From here we will begin python fundamentals

In [6]:
a = 10 
print (a)

10


In [7]:
print (type(a))

<class 'int'>


In [8]:
String = Python 
print(String)

NameError: name 'Python' is not defined

In [9]:
String = "Abdul"
print(String)
print(type(String))

Abdul
<class 'str'>


For String data type we have to put them in double quotes, and that is the reason it is giving error when we assign it first time

In [10]:

new_dt = None
print (new_dt)
print (type(new_dt))

None
<class 'NoneType'>


There is None data type which is a python specific data type

### Multiple Assignments

In [11]:
a , b = 10, 20

print ("The value of a is :", a)
print ("The value of b is :", b)

The value of a is : 10
The value of b is : 20


In [12]:
a = 35
b = 78

print(a)
print(b)

35
78


In [13]:
a = 56
b = 89

a, b = b,a

print("The value of a is :", a)
print("The value of b is :", b)

The value of a is : 89
The value of b is : 56


### Type casting - converting one type of data into another

In [14]:
marks = 71.80
print(marks)
print(type(marks))

71.8
<class 'float'>


In [15]:
int_marks = int(marks)
print(int_marks)
print(type(int_marks))

71
<class 'int'>


In [16]:
intg = 78
print(intg)
print(type(intg))

str_cnv = float(intg)
print(str_cnv)
print(type(str_cnv))

78
<class 'int'>
78.0
<class 'float'>


### Data structures in Python
There are 4 types of Data Structures in Python
1) Tuple
2) List
3) Dictionary
4) Set

### 1. Tuple

In [17]:
first_tuple = (10, 'Messi', 7, 'Ronaldo') # Use round brackets () to create a tuple
print(first_tuple)

(10, 'Messi', 7, 'Ronaldo')


In the above example, \
The 1st value has an index 0 \
2nd value has index 1 \
3rd value has index 2 \
and the 4th value has index 3. This is called indexing (Left to Right indexing)

first_tuple = (10, 'Messi', 7, 'Ronaldo') \
The variable name 'first_tuple' is holding a group of values in a tuple data structure format.

----------------------------------------------------------------------------------
first_tuple[0] - Whenever you use an index to access a value or a group of values, you should use the variable name along with the square bracket.

In [18]:
print(first_tuple[0])

10


In [19]:
first_tuple[0] = 10

TypeError: 'tuple' object does not support item assignment

- We are getting an error above because tuple is an immutable datastructure, which means values once stored in tuple cannot be changed.

-----------------------------------------------------------------------------------------------------------------------
Suppose we want to access the index 0 and index 1, so here we take help of a concept called Slicing.

In [20]:
first_tuple[0:2]

(10, 'Messi')

Here the start index is inclusive which means if we want the element 0, it access the element 0 and then retrive it. But on the other hand the end index is always inclusive only until n-1

In [21]:
# How to access the 1st, 2nd and the 3rd index
first_tuple[1:4]

('Messi', 7, 'Ronaldo')

In [22]:
# Or we can do it like this
first_tuple[1:]

('Messi', 7, 'Ronaldo')

### 2. List

In [23]:
first_list = ["Mark", 102, 23.6, True] # Use only square brackets [] to create list

In [24]:
# Access the first index
first_list[0]

'Mark'

In [25]:
# Access the first 3 index
first_list[0:3]

['Mark', 102, 23.6]

In built method of list

In [26]:
# Adding value at the end of the list
first_list.append("Dawg")

In [27]:
first_list

['Mark', 102, 23.6, True, 'Dawg']

To add the value at a particular index position we will use insert method. Here the first value specifies the index position and the second value specifies the value to be inserted.

In [28]:
first_list.insert(1, "Mouse")

In [29]:
first_list

['Mark', 'Mouse', 102, 23.6, True, 'Dawg']

pop method deletes the value present at the specified index position and also returns the value that has been deleted.

In [30]:
first_list.pop(3)

23.6

In [31]:
first_list

['Mark', 'Mouse', 102, True, 'Dawg']

To replace or update a value.

In [32]:
first_list[1] = 33

In [33]:
first_list

['Mark', 33, 102, True, 'Dawg']

Remove. This method always accepts the value to be removed, and it deletes only the first instances of the specified value from the list.

In [34]:
first_list.append("Mouse")

In [35]:
first_list

['Mark', 33, 102, True, 'Dawg', 'Mouse']

In [36]:
first_list.remove("Mouse")

In [37]:
first_list

['Mark', 33, 102, True, 'Dawg']

In [38]:
first_list[-1]

'Dawg'

In [39]:
first_list[-2:]

[True, 'Dawg']

### 3. Dictionary
Dictionary is a Mutable type of Data Structure. The values are stored along with keys i.e as a key-value pair.
Use curly brackets {} to create dictionary.\
Good practice is to have unique key-values.

In [40]:
age_dict = {'John':20, 'Johnny':22, 'Jack':24, 'Sam':30}

In [41]:
# To access only the keys
age_dict.keys()

dict_keys(['John', 'Johnny', 'Jack', 'Sam'])

In [42]:
# To access only the values
age_dict.values()

dict_values([20, 22, 24, 30])

In [43]:
# To access a particular value, only use it's key
age_dict['Jack']

24

In [44]:
# To update the a particular value, we have to provide both key and the value.
age_dict.update({'Jack':26})

In [45]:
age_dict

{'John': 20, 'Johnny': 22, 'Jack': 26, 'Sam': 30}

In [46]:
# We can also store multiple values for keys
age_dict = {'John': ["john@sl.com", 1000, 20], 'Johny': ["john@sl.com", 1001, 22], 'Sam': ["sam@sl.com", 1002, 24], 'Jack': ["jack@sl.com", 1003, 28]}

In [47]:
age_dict

{'John': ['john@sl.com', 1000, 20],
 'Johny': ['john@sl.com', 1001, 22],
 'Sam': ['sam@sl.com', 1002, 24],
 'Jack': ['jack@sl.com', 1003, 28]}

In [48]:
# To delete a particular value or record
del age_dict["Jack"]

In [49]:
age_dict

{'John': ['john@sl.com', 1000, 20],
 'Johny': ['john@sl.com', 1001, 22],
 'Sam': ['sam@sl.com', 1002, 24]}

In [50]:
# To access multiple values in a dictionary data structure use the 'key' and the 'index'
age_dict['Johny'][0:2]

['john@sl.com', 1001]

### 4. Set - Unordered collection of unique elements

In [51]:
car_brand_sur = ["Audi", "BMW", "Ferrari", "BMW", "Lamborghini", "Benz", "Audi"]
print(car_brand_sur)

['Audi', 'BMW', 'Ferrari', 'BMW', 'Lamborghini', 'Benz', 'Audi']


In [52]:
car_brand_sur_set = set(car_brand_sur)

In [53]:
print(car_brand_sur_set)

{'Audi', 'Lamborghini', 'Ferrari', 'Benz', 'BMW'}


We can absorve from the above that, list supports duplicate values while a set dosen't.

In [54]:
fruit_name_1 = {'Apples', 'Oranges', 'Mangoes', 'Apple', 'Banana'}
print(fruit_name_1)

{'Oranges', 'Apples', 'Banana', 'Mangoes', 'Apple'}


In [55]:
fruit_name_2 = {'Grapes', 'Oranges', 'Peaches', 'Berries', 'Apples'}
print(fruit_name_2)

{'Oranges', 'Berries', 'Apples', 'Grapes', 'Peaches'}


AND operator in SET is equivalent to finding out the intersection of sets.

In [56]:
fruit_name_1 & fruit_name_2

{'Apples', 'Oranges'}

In [57]:
emp_dict = {'Jenny': [1001, 'jenny@sl.com'], 'Peter': [1002, 'peter@sl.com']}

In [58]:
emp_dict['Peter'][1]

'peter@sl.com'

In [59]:
emp_dict.update({'Jenny':[1001, 'jenny@sl.com', 35]})

In [60]:
emp_dict

{'Jenny': [1001, 'jenny@sl.com', 35], 'Peter': [1002, 'peter@sl.com']}

## Loops

In [62]:
num_list = [1,2,3,4]

res_list = []

for i in num_list:
    res_list.append(i*i) # Tab spaces are called indendation in python

print(res_list)

[1, 4, 9, 16]


## Functions
Functions are used to modularise the code and to also reuse the code wherever necessary.

In [63]:
def add(a,b):
    c = a + b
    return c


In [64]:
x = 10
y = 20

output = add(x,y)
print("The sum of x & y is", output)

The sum of x & y is 30


# Numpy
Creating Numpy array or ndarrays

In [65]:
import numpy as np

In [66]:
my_list = [100, 101, 102, 103, 104]

my_ndarray = np.array(my_list)

print(type(my_ndarray))

<class 'numpy.ndarray'>


### Attribute of ndarray - ndim, shape, size, dtype

### ndim

In [67]:
np_city = np.array(["Delhi", "Mumbai", "Kolkata", "Bangalore"])

np_city.ndim

1

In [68]:
np_city_and_states = np.array([["Delhi", "Mumbai", "Kolkata", "Bangalore"], ["Delhi", "Maharashtra", "West Bengal", "Karnataka"]])

np_city_and_states.ndim

2

### Shape

In [69]:
np_city_and_states = np.array([["Delhi", "Mumbai", "Kolkata", "Bangalore"], ["Delhi", "Maharashtra", "West Bengal", "Karnataka"]])

np_city_and_states.shape

(2, 4)

### Size

In [71]:
np_city_and_states.size

8

### Dtype

In [72]:
np_city_and_states.dtype

dtype('<U11')

### Basic Operation on NumPy 

1. Mathematical Operation – Addition, Subtraction, Multiplication, Division and Exponentiation
2. Logical Operation – And, Or Not
3. Comparison Operation – Greater, Greater or equal, Less, Less or equal, Equal, Not equal.


In [73]:
distance = np.array([10, 20, 30, 40, 50])
time = np.array([0.3, 0.5, 0.7, 0.9, 0.8])

speed = distance / time


In [74]:
print(speed)

[33.33333333 40.         42.85714286 44.44444444 62.5       ]


In [75]:
distance = distance * 2
print(distance)

[ 20  40  60  80 100]


In [76]:
distance_2 = np.array([11, 12, 22, 33, 45, 67])

distance - distance_2

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

From the above we could infer that while trying to perform mathematical operations, the ndarrays should be of equal shape

In [77]:
distance_3 = np.array([11, 12, 22, 33, 45])

distance - distance_3

array([ 9, 28, 38, 47, 55])

### How to access array elements using indexing

In [78]:
dist_covered = np.array([[2,4,6,8],[3,6,9,12]])
print("The distance covered by the 2 cars in 4 different rides are: ")
print("-------------------------------------------------------------")
print(dist_covered)



The distance covered by the 2 cars in 4 different rides are: 
-------------------------------------------------------------
[[ 2  4  6  8]
 [ 3  6  9 12]]


In [79]:
dist_covered.ndim

2

    0 1 2 3
0 [[2  4  6  8] \
1  [3  6  9  12]]

Here in this matrix we have row index and column index.

In [80]:
# Here 0 represents first row
dist_covered[0]

array([2, 4, 6, 8])

In [81]:
# Here 1 reperesents 2nd row
dist_covered[1]

array([ 3,  6,  9, 12])

The value in the 1st position indicates the index value of the rows, and the value in the 2nd position indicates the value of the columns. '#' means to select everything.


In [82]:
dist_covered[0,:]

array([2, 4, 6, 8])

In [84]:
dist_covered[1,:]

array([ 3,  6,  9, 12])

In [85]:
# How to retrieve a particular value. Lets say 2
dist_covered[0,0]

2

In [86]:
# To access 3rd column
dist_covered[:,2]

array([6, 9])

In [87]:
# To access the values [2  4] \
#                      [3  6] 
dist_covered[:,:2]

array([[2, 4],
       [3, 6]])

In [88]:
# To access the values [4  6] \
#                      [6  9] 
dist_covered[:,1:3]

array([[4, 6],
       [6, 9]])

### Conditional Selection

In [89]:
dist_covered

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [90]:
dist_covered > 4

array([[False, False,  True,  True],
       [False,  True,  True,  True]])

In [91]:
bool_array = dist_covered > 4

In [92]:
dist_covered[bool_array]

array([ 6,  8,  6,  9, 12])

In [93]:
# Greater than condition
dist_covered[dist_covered > 4]

array([ 6,  8,  6,  9, 12])

In [94]:
# Equal to condition
dist_covered[dist_covered == 6]

array([6, 6])

In [95]:
# Not equal to condition
dist_covered[dist_covered != 4]

array([ 2,  6,  8,  3,  6,  9, 12])

### Universal Function or Ufunc 
These are in-built mathematical functions available in numpy

In [96]:
# Calculating the number of Square root of these number
num_array = np.array([4, 16, 25, 36, 49])

print("Square of these numbers are:")
print(np.sqrt(num_array))

Square of these numbers are:
[2. 4. 5. 6. 7.]


In [97]:
# Calculating the average of the above number

print("The average of these number is")
print(np.mean(num_array))

The average of these number is
26.0


In [98]:
print("Standard Deviation of the above number is:")
print(np.std(num_array))

Standard Deviation of the above number is:
15.582040944625964


In [99]:
print("Variance of the above number is:")
print(np.var(num_array))

print("Median of the above number is:")
print(np.median(num_array))

Variance of the above number is:
242.8
Median of the above number is:
25.0


In [100]:
# To round off the values, we can do that using the round and the ceil function

num_array_2 = np.array([71.6, 56.4, 89.9, 67.4])

In [101]:
np.round([num_array_2])

array([[72., 56., 90., 67.]])

In [102]:
np.ceil([num_array_2])

array([[72., 57., 90., 68.]])

### Shape Manipulation
Here we will be learn to 
- Flatten the array
- Resize the array
- Split the array 
- Stack the array
- Reshape the array.   

In [103]:
dist_covered

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [105]:
# Ravel function will flatten the array into 1 dimentional array
dist_covered.ravel()

array([ 2,  4,  6,  8,  3,  6,  9, 12])

In [106]:
dist_covered.reshape(4,2)

array([[ 2,  4],
       [ 6,  8],
       [ 3,  6],
       [ 9, 12]])

In [107]:
dist_covered.reshape(8,1)

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [ 3],
       [ 6],
       [ 9],
       [12]])

### Splitting the numpy array
Both hsplit and vsplit will result in sub-arrays of equal size

In [108]:
# H-Split

np.hsplit(dist_covered,2)

[array([[2, 4],
        [3, 6]]),
 array([[ 6,  8],
        [ 9, 12]])]

In [111]:
dist_covered_2 = np.array([[2,4,6,8],[3,6,9,12],[1,2,3,4],[9,10,11,12]])
dist_covered_2

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [113]:
# V-split splits the array row wise
np.vsplit(dist_covered_2,2)

[array([[ 2,  4,  6,  8],
        [ 3,  6,  9, 12]]),
 array([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]])]

In [118]:
dist_covered_3 = np.array([[2,6,9,10],[4,7,12,45]])

In [122]:
print(dist_covered)

[[ 2  4  6  8]
 [ 3  6  9 12]]


In [123]:
print(dist_covered_3)

[[ 2  6  9 10]
 [ 4  7 12 45]]


In [119]:
# Stacking the values
# H-Stack

np.hstack((dist_covered, dist_covered_3))

array([[ 2,  4,  6,  8,  2,  6,  9, 10],
       [ 3,  6,  9, 12,  4,  7, 12, 45]])

In [125]:
# V-Stack

print(np.vstack((dist_covered,dist_covered_3)))

[[ 2  4  6  8]
 [ 3  6  9 12]
 [ 2  6  9 10]
 [ 4  7 12 45]]


In [127]:
print(dist_covered)
print("--------------")

print(dist_covered_2)

[[ 2  4  6  8]
 [ 3  6  9 12]]
--------------
[[ 2  4  6  8]
 [ 3  6  9 12]
 [ 1  2  3  4]
 [ 9 10 11 12]]


When we are stacking arrays, make sure both the arrays are of same size. Below it is shown that if we do not follow this rule it will result in an error

In [128]:
np.hstack((dist_covered, dist_covered_2))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 4