## **Missing Indicator**

In [34]:
import numpy as np
import pandas as pd

In [35]:
titanic_df = pd.read_csv('D:/Academics/AI/Data Sets/Titanic.csv', usecols=['Age', 'Fare', 'Survived'])

In [36]:
titanic_df.head()

Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
X = titanic_df.drop(columns=['Survived'])
y = titanic_df['Survived']

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [40]:
X_train.head()

Age     Fare
30   40.0  27.7208
10    4.0  16.7000
873  47.0   9.0000
182   9.0  31.3875
876  20.0   9.8458

In [41]:
from sklearn.impute import SimpleImputer, MissingIndicator

In [42]:
si = SimpleImputer()
X_train_trf = si.fit_transform(X_train)
X_test_trf = si.transform(X_test)

In [43]:
X_train_trf

array([[ 40.        ,  27.7208    ],
       [  4.        ,  16.7       ],
       [ 47.        ,   9.        ],
       ...,
       [ 71.        ,  49.5042    ],
       [ 29.78590426, 221.7792    ],
       [ 29.78590426,  25.925     ]])

In [44]:
from sklearn.linear_model import LogisticRegression
lr_model = LogisticRegression()

lr_model.fit(X_train_trf, y_train)

y_pred = lr_model.predict(X_test_trf)

In [45]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.6145251396648045

In [46]:
mi_model = MissingIndicator()

In [47]:
mi_model.fit(X_train)

MissingIndicator()

In [48]:
mi_model.features_

array([0], dtype=int64)

In [49]:
X_train_missing = mi_model.transform(X_train)

In [50]:
X_train_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [51]:
X_test_missing = mi_model.transform(X_test)

In [52]:
X_test_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [53]:
X_train['Age_NA'] = X_train_missing

In [54]:
X_train.head()

Age     Fare  Age_NA
30   40.0  27.7208   False
10    4.0  16.7000   False
873  47.0   9.0000   False
182   9.0  31.3875   False
876  20.0   9.8458   False

In [55]:
X_test['Age_NA'] = X_test_missing

In [56]:
X_train

Age      Fare  Age_NA
30   40.0   27.7208   False
10    4.0   16.7000   False
873  47.0    9.0000   False
182   9.0   31.3875   False
876  20.0    9.8458   False
..    ...       ...     ...
534  30.0    8.6625   False
584   NaN    8.7125    True
493  71.0   49.5042   False
527   NaN  221.7792    True
168   NaN   25.9250    True

[712 rows x 3 columns]

In [57]:
X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [58]:
from sklearn.linear_model import LogisticRegression

In [59]:
LogR = LogisticRegression()

In [60]:
LogR.fit(X_train_trf2, y_train)
y_pred = LogR.predict(X_test_trf2)

In [61]:
accuracy_score(y_test, y_pred)

0.6312849162011173

In [62]:
SimI = SimpleImputer(add_indicator=True)

In [63]:
X_train = SimI.fit_transform(X_train)

In [65]:
X_test = SimI.transform(X_test)

In [66]:
LogR.fit(X_train_trf2,y_train)
y_pred = LogR.predict(X_test_trf2)

In [67]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6312849162011173